# Generated by Django 5.2.1 on 2025-06-17 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('media_type', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('can_borrow', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Médias',
                'permissions': [('can_view_media', 'Peut voir les détails d’un média')],
            },
        ),
        migrations.CreateModel(
            name='BoardGameClient',
            fields=[
                ('mediaclient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.mediaclient')),
                ('creators', models.CharField(max_length=100)),
                ('is_visible', models.BooleanField(default=True)),
                ('game_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('client.mediaclient',),
        ),
        migrations.CreateModel(
            name='BookClient',
            fields=[
                ('mediaclient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.mediaclient')),
                ('author', models.CharField(max_length=200)),
            ],
            bases=('client.mediaclient',),
        ),
        migrations.CreateModel(
            name='CDClient',
            fields=[
                ('mediaclient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.mediaclient')),
                ('artist', models.CharField(max_length=200)),
            ],
            bases=('client.mediaclient',),
        ),
        migrations.CreateModel(
            name='DVDClient',
            fields=[
                ('mediaclient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.mediaclient')),
                ('producer', models.CharField(max_length=200)),
            ],
            bases=('client.mediaclient',),
        ),
        migrations.CreateModel(
            name='ClientBorrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_at', models.DateTimeField(auto_now_add=True)),
                ('returned', models.BooleanField(default=False)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.mediaclient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
