# Generated by Django 5.2.1 on 2025-06-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientborrow',
            name='role',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
