# Generated by Django 5.2.1 on 2025-05-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediastaff',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
