# Generated by Django 5.2.1 on 2025-05-14 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_mediastaff_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookstaff',
            name='available',
        ),
    ]
