# Generated by Django 5.2.1 on 2025-06-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_mediastaff_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediastaff',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
